# Generated by Django 4.1.3 on 2022-11-16 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=120)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='userprofile/')),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('is_bookman', models.BooleanField(default=False)),
                ('is_driver', models.BooleanField(default=False)),
                ('is_conductor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.trotroaccount')),
            ],
        ),
    ]
