# Generated by Django 4.1.3 on 2022-11-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrotroAccountManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='trotroaccount',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='trotroaccount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='trotroaccount',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='trotroaccount',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='trotroaccount',
            name='is_superadmin',
        ),
        migrations.RemoveField(
            model_name='trotroaccount',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='trotroaccount',
            name='password',
        ),
        migrations.RemoveField(
            model_name='trotroaccount',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='trotroaccount',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trotroaccount',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
