# Generated by Django 4.1.3 on 2022-11-16 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='eg: Kaneshie Station 1', max_length=200)),
                ('phone', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='station/images/')),
                ('location', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Station Point',
                'verbose_name_plural': 'Station Points',
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.stationpoint')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, max_length=120, null=True)),
                ('destination', models.CharField(blank=True, max_length=120, null=True)),
                ('fare', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.stationpoint')),
            ],
            options={
                'verbose_name': 'Transport Fare',
            },
        ),
        migrations.CreateModel(
            name='Bookman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookman', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.stationpoint')),
            ],
            options={
                'verbose_name': 'Bookman',
                'verbose_name_plural': 'Bookmen',
            },
        ),
    ]
